// API 1
GET http://localhost:3007/players/
###

// API 2
GET http://localhost:3007/players/1/
###

// API 3
PUT http://localhost:3007/players/1/
Content-Type: application/json

{
  "playerName": "Ram"
}
###

// API 4
GET http://localhost:3007/matches/1/
###

// API 5
GET http://localhost:3007/players/1/matches/
###

// API 6
GET http://localhost:3007/matches/1/players/
###

// API 7
GET http://localhost:3007/players/1/playerScores/
###
